-- MySQL Script generated by MySQL Workbench
-- Sat Jun 25 00:03:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema paymybuddy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `paymybuddy` ;

-- -----------------------------------------------------
-- Schema paymybuddy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paymybuddy` DEFAULT CHARACTER SET utf8mb4 ;
USE `paymybuddy` ;

-- -----------------------------------------------------
-- Table `paymybuddy`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy`.`user` ;

CREATE TABLE IF NOT EXISTS `paymybuddy`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` LONGTEXT NULL,
  `email` VARCHAR(45) NULL,
  `balance` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `paymybuddy`.`connection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy`.`connection` ;

CREATE TABLE IF NOT EXISTS `paymybuddy`.`connection` (
  `user_iduser` INT NOT NULL,
  `user_iduser1` INT NOT NULL,
  PRIMARY KEY (`user_iduser`, `user_iduser1`),
  INDEX `fk_user_has_user_user1_idx` (`user_iduser1` ASC) VISIBLE,
  INDEX `fk_user_has_user_user_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_user_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `paymybuddy`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`user_iduser1`)
    REFERENCES `paymybuddy`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymybuddy`.`bankAccountTransaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy`.`bankAccountTransaction` ;

CREATE TABLE IF NOT EXISTS `paymybuddy`.`bankAccountTransaction` (
  `idbank_account_transaction` INT NOT NULL AUTO_INCREMENT,
  `bank_account` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idbankAccountTransaction`),
  INDEX `fk_bankAccountTransaction_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_bankAccountTransaction_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `paymybuddy`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paymybuddy`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `paymybuddy`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `paymybuddy`.`Transaction` (
  `idTransaction` INT NOT NULL AUTO_INCREMENT,
  `senderEmail` VARCHAR(45) NULL,
  `receiverEmail` VARCHAR(45) NULL,
  `amount` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `iduser` INT NOT NULL,
  PRIMARY KEY (`idTransaction`),
  INDEX `fk_Transaction_user1_idx` (`iduser` ASC) VISIBLE,
  CONSTRAINT `fk_Transaction_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `paymybuddy`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
